/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Hash1;
import EDD.HashTable;
import EDD.LectorDeTxt;

/**
 * La clase {@code Menu} representa la interfaz principal de la aplicación de
 * gestión de resúmenes. Permite al usuario acceder a diferentes funciones como
 * búsqueda, carga y análisis de resúmenes.
 *
 * @author Chris
 */
public class Menu extends javax.swing.JFrame {

    HashTable hashtable;
    Hash1 hash;

    /**
     * Crea una nueva instancia de la clase {@code Menu}.
     */
    public Menu() {
        initComponents();
        this.hashtable = new HashTable(30);
        this.hash = new Hash1(120);
        LectorDeTxt lector = new LectorDeTxt(this.hashtable, this.hash);
        String[] archivos = {"archivo1.txt", "archivo2.txt", "archivo3.txt", "archivo4.txt"};
        for (int i = 0; i < archivos.length; i++) {
            lector.leerResumen(archivos[i]);
        }
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        añadir = new javax.swing.JLabel();
        resumen = new javax.swing.JLabel();
        buscarPalabraClave = new javax.swing.JLabel();
        analizar = new javax.swing.JLabel();
        buscarAutor = new javax.swing.JLabel();
        botonBuscarAutor = new javax.swing.JButton();
        botonAnalizar = new javax.swing.JButton();
        botonBuscarPalabraClave = new javax.swing.JButton();
        botonAgregar = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        añadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Añadir.png"))); // NOI18N
        jPanel1.add(añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 30, 40));

        resumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Resumen.png"))); // NOI18N
        jPanel1.add(resumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 70, 80));

        buscarPalabraClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BuscarPalabraClave.png"))); // NOI18N
        jPanel1.add(buscarPalabraClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 70, 80));

        analizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Analizar.png"))); // NOI18N
        jPanel1.add(analizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 60, 70));

        buscarAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BuscarAutor.png"))); // NOI18N
        jPanel1.add(buscarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 60, 70));

        botonBuscarAutor.setBackground(new java.awt.Color(0, 0, 0));
        botonBuscarAutor.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botonBuscarAutor.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscarAutor.setText("Buscar por autor");
        botonBuscarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarAutorActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 220, 70));

        botonAnalizar.setBackground(new java.awt.Color(0, 0, 0));
        botonAnalizar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botonAnalizar.setForeground(new java.awt.Color(255, 255, 255));
        botonAnalizar.setText("Analizar resumen");
        botonAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnalizarActionPerformed(evt);
            }
        });
        jPanel1.add(botonAnalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 220, 70));

        botonBuscarPalabraClave.setBackground(new java.awt.Color(0, 0, 0));
        botonBuscarPalabraClave.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botonBuscarPalabraClave.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscarPalabraClave.setText("Buscar por palabra clave");
        botonBuscarPalabraClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarPalabraClaveActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscarPalabraClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 220, 70));

        botonAgregar.setBackground(new java.awt.Color(0, 0, 0));
        botonAgregar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregar.setText("Agregar resumen");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 220, 70));

        Titulo.setFont(new java.awt.Font("Ebrima", 0, 30)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Escoge una opción:");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        botonSalir.setBackground(new java.awt.Color(0, 0, 0));
        botonSalir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 100, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción realizada al presionar el botón "Buscar por Autor".
     *
     * @param evt el evento de acción
     */
    private void botonBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarAutorActionPerformed
        this.setVisible(false);

        Menu menu = new Menu();

        BuscarAutor buscar = new BuscarAutor(menu);

        buscar.setVisible(true);
    }//GEN-LAST:event_botonBuscarAutorActionPerformed

    /**
     * Acción realizada al presionar el botón "Buscar por Palabra Clave".
     *
     * @param evt el evento de acción
     */
    private void botonBuscarPalabraClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarPalabraClaveActionPerformed
        this.setVisible(false);

        Menu menu = new Menu();

        BuscarPalabraClave buscar = new BuscarPalabraClave(menu);

        buscar.setVisible(true);
    }//GEN-LAST:event_botonBuscarPalabraClaveActionPerformed

    /**
     * Acción realizada al presionar el botón "Agregar Resumen".
     *
     * @param evt el evento de acción
     */
    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        this.setVisible(false);

        Menu menu = new Menu();

        Cargar cargar = new Cargar(menu);

        cargar.setVisible(true);
    }//GEN-LAST:event_botonAgregarActionPerformed

    /**
     * Acción realizada al presionar el botón "Analizar Resumen".
     *
     * @param evt el evento de acción
     */
    private void botonAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnalizarActionPerformed
        this.setVisible(false);

        Menu menu = new Menu();

        Analizar analizar = new Analizar(menu);

        analizar.setVisible(true);
    }//GEN-LAST:event_botonAnalizarActionPerformed

    /**
     * Acción realizada al presionar el botón "Salir".
     *
     * @param evt el evento de acción
     */
    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel analizar;
    private javax.swing.JLabel añadir;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAnalizar;
    private javax.swing.JButton botonBuscarAutor;
    private javax.swing.JButton botonBuscarPalabraClave;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel buscarAutor;
    private javax.swing.JLabel buscarPalabraClave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resumen;
    // End of variables declaration//GEN-END:variables
}
